version: '3.3'

services:
  postgres:
    image: postgres:15.1
    container_name: wispro-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
